spring:
  application:
    name: pgvector-rag-starter
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
rag:
  embedding:
    model: text-embedding-3-small
    dimension: 1536
